### ISSUE TITLE
[!IMPORTANT] fix openssl for Windows

### ISSUE THREAD

**Issue by pmq20** [pmq20/ruby-packer#111]
```
Traceback (most recent call last):
        11: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:947:in `<main>'
        10: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:947:in `each'
         9: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:950:in `block in <main>'
         8: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:799:in `block in <main>'
         7: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:835:in `install_default_gem'
         6: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:835:in `each'
         5: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:845:in `block in install_default_gem'
         4: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:279:in `open_for_install'
         3: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/tool/rbinstall.rb:846:in `block (2 levels) in install_default_gem'
         2: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/lib/rubygems/specification.rb:2426:in `to_ruby'
         1: from C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Users/pmq20/AppData/Local/Temp/rubyc/ruby-2.7.1a/lib/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- openssl (LoadError)
```

**Comment by pmq20** [comment]
fixed in https://github.com/pmq20/ruby-packer/commit/91ff78080b9c4a919015b4dedaa5e4c450c1a927 and https://github.com/pmq20/ruby-packer/commit/91ff78080b9c4a919015b4dedaa5e4c450c1a927
