### ISSUE TITLE
Windows, couldn't recognize gem

### ISSUE THREAD

**Issue by kersmu** [pmq20/ruby-packer#125]
However when I wanted to compile a graphical application  (made with FXRuby), the build was succesful so I got the exe file, but when I run it I got this error message: 

```
Traceback (most recent call last):
        2: from /__enclose_io_memfs__/local/draw_polygon.rb:1:in `<main>'
        1: from /__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- fox16 (LoadError)
```

It says that `cannot load such file -- fox16` ('fox16' = FXRuby libary from the fxruby gem). I think that there is a problem with gem importing into the executable.
How to import a gem file to this package? Do you know any solution for this? 

Thanks for any help.
Samu

**Comment by pmq20** [comment]
@kersmu Hi Samuel, could you share the project being compiled (or a reduced version minimal to reproduce the issue)? Thank you!

**Comment by kersmu** [comment]
Hi @pmq20!
Thank you for building this project up. It is a lifesafer jacket. But my problem with the above issue is that If I compile it than I get a program which basically not works. 😐. But the good new for you is that I know where I missed 😁 (hope so). But unfortunately, I don't really know how to solve it in practice. 

So, about my program:
1.It's using a `gem` that I've downloaded with rubygems (`fxruby`)
2. It is a GUI app
3. It is a single `.rbw` file 
4. I don't use any bundler solution in it to manage gems(I believe that this is the reason why I get a require/load error concerning the fxruby gem, after I compilled my program) 

So my question is : 
Do you know any solution to require that gem in the rubyc generated .exe file?, (in that packed ruby environment) because if I'm correct then this is the root of my problem) 
Or in general every kind of gem to include in the rubyc generated .exe file's ruby environment?
Do I need to use bundler? 
Or maybe generate Gemfile? 
I am not very familiar with Bundler though, but I can learn it if I need. 😁

I would be grateful for any suggestion on this solvable problem. 

And again thank you for your effort. 

Greetings, 
Samuel from Budapest 😁

**Comment by kersmu** [comment]
Hi @pmq20! I reached the next level in my progression!  😁Yayy!!

This is a reply for my previous comment. I have good a new and a bad. The good new is that I figured out how to include gems  with bundler (I initialized a GEMFILE and copy there my gem list. and the rest is done by rubyc). The bad new is that it is not working with specific gems having `.dll` libaries* (this is only for windows though) so It is painful :( .

 There is an example: `fxruby` gem. 
 - In unix it just need some other package to install before installing the gem.  
 - In windows you just need to simply install the gem. (since the gem includes the compiled libary files (`.dll files`))
There is the github package and the detailed installation of the toolkit:  https://github.com/larskanis/fxruby

We know that in windows the common installation method of ruby is via the **RubyInstaller** what is uses **MSYS2/MinGW**. BUT The runnable .exe file generated by rubyc on the contrary, uses _`x64-mswin64_140`_ ruby environment and not `_x64-mingw32_` what is the most used environment in a Win machine. 

So when I compilled the ruby (+ a GEMFILE that include the needed gem list) code with rubyc the console outputed an error: that the `.ddl` files are missing so it couldn't install `fxruby` with `bundle install` command. 
- In my opinion this is due to the lack of the required .dll files to install the gem, because when I installed fxruby gem on my machine, in the local gemfolder the name of the fxruby.gem was this:  `fxruby-1.6.42-x64-mingw32` ,but when rubyc did the installation it show that it downloads only `fxruby-1.6.42` version of the gem. Unfortunatelly fxruby-1.6.42 doesn't come with the required .dll libaries.

So if I'am correct then this is the source of this issue

@pmq20 Do you know any solution to include the` .ddl` files within the bundle install command in the rubyc?
Is it possible to include .dll files while compiling with rubyc in windows? 
Maybe with the `--make-args=ARGS` attribute to inlcude the` .dll`-s in the compiler?
Or simply just change the name of the `fxruby` gem version in the gem file to `fxruby-1.6.42-x64-mingw32`?

Thank you so far for your time!
And of course do you know any way for me to help with this issue? I would like to help if that is possible.😁

Greetings, 
Samuel from Budapest 😁

**Comment by pmq20** [comment]
@kersmu Hi Samuel, glad to receive your feedback! I have read the entire post. I believe that to compile and distribute GUI applications via the packer is a promising feature in the future, so I want to see it work too.

By design, `dll` files are supposed to work because they would be packed in the same in-memory SquashFS and be extracted to a temporary location and redirect the `dlopen()`-ed (or `LoadLibrary()`-ed in the case of Windows) call to that temporary location. That logic should have been implemented in libsquash, though I am not sure if it still works since I have not been actively testing C extensions for a while, nor is it part of the CI. I plan to work on it this weekend. This might also be related to #122 ; cc @bryanp

Meanwhile the case of this issue might be more complicated as you mentioned that only MinGW `dll` was available. It is indeed a design decision of Ruby Packer to not use MinGW (cf. "Windows is supported via the native Windows API; there are no MSYS2/MinGW/Cygwin dependencies" of readme). Is there a native `dll` or can you compile a native `dll` using, say, Visual Studio's "x64 Native Tools Command Prompt" for `fxruby`? I imagine there would be problems if a `mingw32` dll was loaded inside a native app that does not depend on MinGW.

**Comment by kersmu** [comment]
"@kersmu Hi Samuel, glad to receive your feedback! I have read the entire post. I believe that to compile and distribute GUI applications via the packer is a promising feature in the future, so I want to see it work too."

@pmq20 I totally agree with you! 
In my case, my ruby application is a opengl based graphical (though it's very simple, just a rotating cube with texture) engine. But it's work's!!! And entirelly written in ruby. And you know, the interesting part of it was when I did run it (just the ruby file... yet) surprisingly it was fast but how! no lag! no lag! It was definitely a pleasant suprise from ruby. 😂 It's a fast language! 😂😂😂.... 

Okay just joking. It was because the video card.

But apart from this, I'm not sure whether the `.dll` files are compiled in MinGw. I just copied all of them from the # `fxruby-1.6.42-x64-mingw32`` gems's folder into a separate folder to keep them safe and in one place for further use and build. 

If you interested in the list I will send you  it tomorrow. 

Anyway, your project will be good! 

Greetings,
Samuel from Budapest 😁
