### ISSUE TITLE
Unable to get working build on Windows

### ISSUE THREAD

**Issue by stahnma** [pmq20/ruby-packer#22]
I've been struggling for a few days with Windows, and finally got a clean build of my project, however it doesn't run. In trying to elimenate my project as the problem, I took a well-known rubygem (httparty) and attempted to build a single executable using ruby-packer. Again, it built but I was unable to get it to run, as it has some type of gemspec load error. 

Steps to reproduce:

1. clone httparty
2. `rubyc -c bin/httparty`
3. Attempt to run `a.exe`

Output:
```

C:\Users\Administrator\Downloads\httparty>a.exeC:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem httparty (>= 0.a) (Gem::GemNotFoundException)        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'        from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/httparty:22:in `<main>'2C:\Users\Administrator\Downloads\httparty>C:\Users\Administrator\Downloads\httparty>a.exeC:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem httparty (>= 0.a) (Gem::GemNotFoundException)        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'        from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/httparty:22:in `<main>'
C:\Users\Administrator\Downloads\httparty>

C:\Users\Administrator\Downloads\httparty>a.exeC:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem httparty (>= 0.a) (Gem::GemNotFoundException)        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'        from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/httparty:22:in `<main>'
C:\Users\Administrator\Downloads\httparty>
```

This system is Windows 2016 x64, Visual Studio 2015u3 community, choco installed bison, squashfs tried from both the link on the README with this project and from chocoloatey.

**Comment by lawsonry** [comment]
Hey, good news and bad news. Good news is that I ran into this problem and it turned out to be something about the way I had the folders setup. Bad news is that I'm on a macbook for the rest of the week/weekend, so can't help you anytime soon. Have you checked folder permissions? I think that was the first thing I did.
