### ISSUE TITLE
undefined symbol: Init_liboga - /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/oga-2.14/lib/liboga.so (LoadError)

### ISSUE THREAD

**Issue by tannevaled** [pmq20/ruby-packer#46]
```
Traceback (most recent call last):
	7: from /__enclose_io_memfs__/local/exe/lmod-ruby-installer:30:in `<main>'
	6: from /__enclose_io_memfs__/local/exe/lmod-ruby-installer:30:in `require'
	5: from /__enclose_io_memfs__/local/lib/lri.rb:3:in `<top (required)>'
	4: from /__enclose_io_memfs__/local/lib/lri.rb:3:in `require'
	3: from /__enclose_io_memfs__/local/lib/lri/archives.rb:3:in `<top (required)>'
	2: from /__enclose_io_memfs__/local/lib/lri/archives.rb:3:in `require'
	1: from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/oga-2.14/lib/oga.rb:18:in `<top (required)>'
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/oga-2.14/lib/oga.rb:18:in `require': ./lmod-ruby-installer: undefined symbol: Init_liboga - /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/oga-2.14/lib/liboga.so (LoadError)
```
```
$ strings /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/oga-2.14/lib/liboga.so| grep Init
Init_liboga_xml_lexer
Init_liboga
InitVM(ext) {void InitVM_ ##ext(void);InitVM_ ##ext();}
Init_stack(addr) ruby_init_stack(addr)
Init_liboga_xml_lexer
Init_liboga
Init_liboga_xml_lexer
Init_liboga
```

**Comment by tannevaled** [comment]
i replaced oga by nokogiri and now i have the next errors, alternatively

/__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi.rb:6:in `require': ./lmod-ruby-installer: undefined symbol: Init_ffi_c - /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi_c.so (LoadError)

/__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library '/__enclose_io_memfs__/local/vendor/usr/lib64/libarchive.so.13.1.2': /__enclose_io_memfs__/local/vendor/usr/lib64/libarchive.so.13.1.2: cannot open shared object file: No such file or directory (LoadError)

but /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi_c.so and /__enclose_io_memfs__/local/vendor/usr/lib64/libarchive.so.13.1.2 are there in the squashfs

**Comment by CAMOBAP** [comment]
@tannevaled have you managed to solve the problem?
