### ISSUE TITLE
Pry & readline causing problems

### ISSUE THREAD

**Issue by matti** [pmq20/ruby-packer#52]
```
Pry.start
```
works fine on the machine that compiled the package, but on another machine hitting arrow key just rings the terminal bell.

Once I installed "rb-readline" gem it worked on both

**Comment by SwagDevOps** [comment]
You could also use ``pry-coolline``.

You could, also, see this issue: https://github.com/pry/pry/issues/1579
I ignore, if ``ruby-packer`` allows to use a ``--with-readline`` build option… because, in this case, it (probably) should provide its own version of ``readline``.

**Comment by iamsimakov** [comment]
hi, guys, does anybody know how to force working `./a.out console` when compiling Rails application?
now I see error:
```
/__enclose_io_memfs__/lib/ruby/2.4.0/irb/locale.rb:112:in `load': No such file to load -- irb/error.rb (LoadError)
	from /__enclose_io_memfs__/lib/ruby/2.4.0/irb/init.rb:121:in `init_error'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/irb/init.rb:18:in `setup'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/irb.rb:378:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:62:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:17:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:97:in `perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	from /__enclose_io_memfs__/local/bin/rails:9:in `require'
	from /__enclose_io_memfs__/local/bin/rails:9:in `<main>'

```

thanks
