### ISSUE TITLE
cannot load such file -- tty-prompt

### ISSUE THREAD

**Issue by Awatatah** [pmq20/ruby-packer#53]
Hello, after I run the compiler I try to execute the file `./a.out` but I receive the below error for gem `tty-prompt`. I've also received the same for `pry`

in my `.rb` file I have 

```
require 'tty-prompt'
```

and I receive error

> /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- tty-prompt (LoadError)
from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /__enclose_io_memfs__/local/prerequisite_runner.rb:4:in `<main>'

I'm using `rubyc 0.4.0` and `ruby 2.4.1p111`

**Comment by tresacton** [comment]
Also experiencing this issue:

```/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mail (LoadError)
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /__enclose_io_memfs__/local/test-scriptl.rb:4:in `<main>'```

**Comment by Awatatah** [comment]
I tried another application and still receive dependency errors

```
/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- aws-sdk (LoadError)
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /__enclose_io_memfs__/local/organize_logs.rb:1:in `<top (required)>'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /__enclose_io_memfs__/local/manual_start.rb:2:in `<main>'
```

**Comment by iamsimakov** [comment]
hi @Awatatah in my case I use `rails runner '<some ruby code>'` for one line script. 
and about your question. Maybe create Gemfile with one dependency `aws-sdk`, one Gemfile.lock from it and simple one line ruby script with text: `require `aws-sdk``. Run `bundle`, start script. And after trying to build it with rubyc.

**Comment by iamsimakov** [comment]
#39
