### ISSUE TITLE
Cant run a.out server after compile

### ISSUE THREAD

**Issue by andresmu** [pmq20/ruby-packer#59]
this is my issue:

$ ./a.out server
=> Booting Puma
=> Rails 5.1.6 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/bundler/gems/rb-inotify-be4cf88b4dab/lib/rb-inotify/watcher.rb:74:in `initialize': No such file or directory - Failed to watch "/__enclose_io_memfs__/local/config/locales" (Errno::ENOENT)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/bundler/gems/rb-inotify-be4cf88b4dab/lib/rb-inotify/notifier.rb:190:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/bundler/gems/rb-inotify-be4cf88b4dab/lib/rb-inotify/notifier.rb:190:in `watch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/bundler/gems/rb-inotify-be4cf88b4dab/lib/rb-inotify/notifier.rb:204:in `watch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:32:in `_configure'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:45:in `block in configure'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `configure'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:63:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/evented_file_update_checker.rb:94:in `boot!'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/evented_file_update_checker.rb:65:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/i18n_railtie.rb:59:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/i18n_railtie.rb:59:in `initialize_i18n'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/i18n_railtie.rb:23:in `block in <class:Railtie>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:66:in `block in <module:Finisher>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
	from /__enclose_io_memfs__/local/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:24:in `app'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:42:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:135:in `block in perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	from /__enclose_io_memfs__/local/bin/rails:9:in `require'
	from /__enclose_io_memfs__/local/bin/rails:9:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /__enclose_io_memfs__/local/bin/spring:15:in `<top (required)>'
	from /__enclose_io_memfs__/local/bin/rails:3:in `load'
	from /__enclose_io_memfs__/local/bin/rails:3:in `<main>'
I tried somethings but cant understand my problem, thanks for any help.

**Comment by andresmu** [comment]
@iamsimakov Thank you, i tried:

./a.out s -e=production
=> Booting Puma
=> Rails 5.1.6 application starting in production 
=> Run `rails server -h` for more startup options
Exiting
/__enclose_io_memfs__/local/config/initializers/redis-browser.rb:3:in `<top (required)>': uninitialized constant RedisBrowser (NameError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:654:in `load_config_initializer'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:611:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
	from /__enclose_io_memfs__/local/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:24:in `app'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:44:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:135:in `block in perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	from /__enclose_io_memfs__/local/bin/rails:9:in `require'
	from /__enclose_io_memfs__/local/bin/rails:9:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /__enclose_io_memfs__/local/bin/spring:15:in `<top (required)>'
	from /__enclose_io_memfs__/local/bin/rails:3:in `load'
	from /__enclose_io_memfs__/local/bin/rails:3:in `<main>'


have other issue

**Comment by andresmu** [comment]
@iamsimakov fixed config to production env, thanks a lot
