### ISSUE TITLE
enclose_io_memfs文件过大

### ISSUE THREAD

**Issue by eson001** [pmq20/ruby-packer#61]
-rw-r--r-- 1 root root 1.0G 9月   5 18:50 enclose_io_memfs.c

**Comment by iamsimakov** [comment]
which full path of this file? I think it is needed only for building process but this file is not included to build.

**Comment by eson001** [comment]
@iamsimakov do you have qq?

**Comment by eson001** [comment]
-> CI=true PATH=/tmp/rubyc/ruby_install_1/bin:.:/home/songjian/jdk1.8.0_171/bin:/usr/local/rvm/gems/ruby-2.3.1/bin:/usr/local/rvm/gems/ruby-2.3.1@global/bin:/usr/local/rvm/rubies/ruby-2.3.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/rvm/bin:/bin/:/usr/bin ENCLOSE_IO_USE_ORIGINAL_RUBY=1 ENCLOSE_IO_RUBYC_1ST_PASS=1 ENCLOSE_IO_RUBYC_2ND_PASS='' /tmp/rubyc/ruby_install_1/bin/gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /tmp/rubyc/ruby_install_1/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /tmp/rubyc/ruby_install_1/bin/ruby
  - EXECUTABLE DIRECTORY: /tmp/rubyc/ruby_install_1/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /tmp/rubyc/ruby_install_1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /tmp/rubyc/ruby_install_1/lib/ruby/gems/2.5.0
     - /root/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /tmp/rubyc/ruby_install_1/bin
     - .
     - /home/songjian/jdk1.8.0_171/bin
     - /usr/local/rvm/gems/ruby-2.3.1/bin
     - /usr/local/rvm/gems/ruby-2.3.1@global/bin
     - /usr/local/rvm/rubies/ruby-2.3.1/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /snap/bin
     - /usr/local/rvm/bin
     - /bin/
     - /usr/bin
/home/desen/rubyc-src/ruby-packer/ruby-compiler/lib/compiler.rb:824:in `block in prepare_local': undefined local variable or method `gemspec' for #<Compiler:0x0000000176e3b8> (NameError)
Did you mean?  gemspecs
        from /home/desen/rubyc-src/ruby-packer/ruby-compiler/lib/compiler/utils.rb:86:in `block in chdir'
        from /home/desen/rubyc-src/ruby-packer/ruby-compiler/lib/compiler/utils.rb:86:in `chdir'
        from /home/desen/rubyc-src/ruby-packer/ruby-compiler/lib/compiler/utils.rb:86:in `chdir'
        from /home/desen/rubyc-src/ruby-packer/ruby-compiler/lib/compiler.rb:808:in `prepare_local'
        from /home/desen/rubyc-src/ruby-packer/ruby-compiler/lib/compiler.rb:681:in `run!'
        from ./rubyc:143:in `<main>'

**Comment by iamsimakov** [comment]
do you use `rubyc v0.4.0`?

**Comment by eson001** [comment]
yes
