### ISSUE TITLE
Cannot compile projects involving Bundler.

### ISSUE THREAD

**Issue by jrkarnes** [pmq20/ruby-packer#84]
I have been attempting to compile a private project using Bundler 2.0.1 to manage the database gem dependencies that this project requires.

I can build the gem, and when installed, its executables run just fine... but I would like an executable that is transportable without having to install a ruby environment on the target system which is why I have been trying to use this project.

Unfortunately, for whatever reason the project refuses to be built.

When I remove the Bundler from my project (and thus the `Gemfile.lock` file), your tool works. When Bundler is present, your tool fails.

I have gone through the compile logs and figured out that your tool is installing bundler 1.15.3 after I invoke the builder:

```
Successfully installed bundler-1.15.3
1 gem installed
-> Running [{"CI"=>"true", "PATH"=>"/var/folders/1w/6wt0nysn2lx6cb_nb3_7b8km7hvl82/T/rubyc/ruby-2.4.1-0.4.0/build/bin:/Users/jkarnes/bin:/Users/jkarnes/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/jkarnes/.nvm/versions/node/v11.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jkarnes/bin:/Users/jkarnes/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/jkarnes/.nvm/versions/node/v11.12.0/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "bundle", "install"]
The latest bundler is 2.0.1, but you are currently running 1.15.3.
To update, run `gem install bundler`
You must use Bundler 2 or greater with this lockfile.
Failed running [{"CI"=>"true", "PATH"=>"/var/folders/1w/6wt0nysn2lx6cb_nb3_7b8km7hvl82/T/rubyc/ruby-2.4.1-0.4.0/build/bin:/Users/jkarnes/bin:/Users/jkarnes/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/jkarnes/.nvm/versions/node/v11.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jkarnes/bin:/Users/jkarnes/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/jkarnes/.nvm/versions/node/v11.12.0/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "bundle", "install"]
MacBook-Pro:database_tools jkarnes$ which bundler
/Users/jkarnes/.rbenv/shims/bundler
MacBook-Pro:database_tools jkarnes$ bundler --version
Bundler version 2.0.1
```

I have tried running this in the context of Ruby 2.4.0, and 2.6.2. I have upgraded rubygems with `gem upgrade --system` and still nothing.

Please let me know what you would like to additionally see or have me do to solve this issue.

**Comment by iamsimakov** [comment]
hi, i use rubyc too, thanks creators. 
Installation ruby on target system is not necessary. You need just running binary file.
Or show your log starting app on target machine.
Gemfile and lock files need rubyc to pack ypur gems into virtual fs inside binary file.

**Comment by jrkarnes** [comment]
> Installation ruby on target system is not necessary. You need just running binary file.
Ruby is an interpreted language and by its nature cannot produce a binary file. That's why the creation of the executable is such a big deal. By its nature, you will need an interpreter to run the code. Enclose.io is just wrapping your code up with base ruby and then doing some magic to cause it to be the entrypoint of the interpreter loop.

**Comment by iamsimakov** [comment]
Oh, i'm sorry, it seems now i understood your problem, that we can not use actual version of bundler, ie rubyc uses not updated bundler version.

**Comment by jrkarnes** [comment]
Correct. It seems like `rubyc` is using a version of `Bundler` that is predefined somewhere in the `rubyc` application rather than looking for the system version of bundler first before downloading.

**Comment by jcouball** [comment]
@jrkarnes try deleting `Gemfile.lock` before running `rubyc`

**Comment by GregPK** [comment]
> @jrkarnes try deleting `Gemfile.lock` before running `rubyc`

I had a different issue and this worked for me. Specifically the output binary seemed not to have any gems linked to it. When running the binary I got

```
/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thor (LoadError)
```

Deleting `Gemfile.lock` solved it. Leaving it here for someone else.

**Comment by jrkarnes** [comment]
I'll give it a shot and report back with results.

**Comment by HarlemSquirrel** [comment]
I ran into this problem as well. I think the issue lies with using the last released version which at the moment dates back to 2017 and even mentions Bundler is set to 1.15.3 https://github.com/pmq20/ruby-packer/releases/tag/v0.4.0

I got farther along by building rubyc myself from the master branch. 

Now I have the following which is likely not related.
```
/__enclose_io_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:41:in `gem': wrong number of arguments (given 0, expected 1+) (ArgumentError)
```

**Comment by d4rky-pl** [comment]
Latest master is still using Bundler 1.15.3, do not use Bundler 2.x as it's backwards incompatible
