### ISSUE TITLE
Error compiling rails app

### ISSUE THREAD

**Issue by treyvfromlbc** [pmq20/ruby-packer#85]
-> Running [{"CI"=>"true", "PATH"=>"C:/Users/callm/AppData/Local/Temp/rubyc/ruby-2.4.1-0.4.0/build/bin:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\MSBuild\\14.0\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools;C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\VCPackages;C:\\Program Files (x86)\\HTML Help Workshop;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x86;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6 Tools\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files (x86)\\QuickTime\\QTSystem\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\GnuWin32\\bin;C:\\Ruby26-x64\\bin;C:\\Users\\callm\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\heroku\\bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "gem", "install", "C:/Users/callm/AppData/Local/Temp/rubyc/ruby-2.4.1-0.4.0/vendor/bundler-1.15.3.gem", "--verbose", "--no-rdoc", "--no-ri"]
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc
Failed running [{"CI"=>"true", "PATH"=>"C:/Users/callm/AppData/Local/Temp/rubyc/ruby-2.4.1-0.4.0/build/bin:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\MSBuild\\14.0\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools;C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\VCPackages;C:\\Program Files (x86)\\HTML Help Workshop;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x86;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6 Tools\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files (x86)\\QuickTime\\QTSystem\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\GnuWin32\\bin;C:\\Ruby26-x64\\bin;C:\\Users\\callm\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\heroku\\bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "gem", "install", "C:/Users/callm/AppData/Local/Temp/rubyc/ruby-2.4.1-0.4.0/vendor/bundler-1.15.3.gem", "--verbose", "--no-rdoc", "--no-ri"]

**Comment by treyvfromlbc** [comment]
Fixed that issues by rolling back rubygems to 2.5.

God that issue seems so long ago. Now I have a new issue that I've been dealing with for days.

"fatal error c1060: compiler is out of heap space" while compiling memfs.

**Comment by iamsimakov** [comment]
in my case when i compile preparing tools (it seems prelude.c) it uses 10GB memory

**Comment by treyvfromlbc** [comment]
> in my case when i compile preparing tools (it seems prelude.c) it uses 10GB memory
> 
> #74

I finally got past that error. I did it by increasing the paging file space to max 90000. The compiler finally(and I can't stress the word _finally_ enough) ran through completion.

But...now I'm getting another error when I try to run the output exe. 

$ ./a.exe server
c:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from c:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/__enclose_io_memfs__/local/config/boot.rb:3:in `<top (required)>'
        from /__enclose_io_memfs__/local/bin/rails:3:in `require_relative'
        from /__enclose_io_memfs__/local/bin/rails:3:in `<main>'
