### ISSUE TITLE
Ms 

### ISSUE THREAD

**Issue by vitalykarasik** [pmq20/ruby-packer#87]

**Comment by vitalykarasik** [comment]
First, two basic questions:

1. Does rubyc version should correlate with Ruby's version?
2. 32 vs 64 bit?  As far I as see from MS Studio 2019 command prompt, I'm using 32bit version. Is it OK?

My goal is to compile my custom gem, and I'm getting the following error:

`C:\Users\Administrator\source\repos>C:\Users\Administrator\Desktop\rubyc-v0.4.0-x64.exe  --gem=cnvrg --gem-version=0.8.8 cnvrg
Ruby Compiler (rubyc) v0.4.0
- entrance: cnvrg
- options: {:gem=>"cnvrg", :gem_version=>"0.8.8", :make_args=>"-j4", :output=>"C:/Users/Administrator/source/repos/a.exe", :tmpdir=>"C:/Users/ADMINI~1/AppData/Local/Temp/2/rubyc"}

-> mkdir -p C:/Users/ADMINI~1/AppData/Local/Temp/2/rubyc
-> rm -rf C:/Users/ADMINI~1/AppData/Local/Temp/2/rubyc/cnvrg-0.8.8
-> mkdir -p C:/Users/ADMINI~1/AppData/Local/Temp/2/rubyc/cnvrg-0.8.8
-> cd C:/Users/ADMINI~1/AppData/Local/Temp/2/rubyc/cnvrg-0.8.8
Downloading http://rubygems.org/downloads/cnvrg-0.8.8.gem
C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- socket.so (LoadError)
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/socket.rb:3:in `<top (required)>'`
